<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Amarnath" failures="1" tests="2" name="Default test(failed)" time="23.297" errors="0" timestamp="2025-08-28T18:15:31 IST">
  <testcase classname="HRM_Framework.HRM_Framework.Login_Test" name="validLogin" time="4.088"/>
  <testcase classname="HRM_Framework.HRM_Framework.Login_Test" name="invalidLogin" time="5.233">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at HRM_Framework.HRM_Framework.Login_Test.invalidLogin(Login_Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Default test(failed) -->
