<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Amarnath" failures="1" tests="2" name="Run on Chrome" time="19.177" errors="0" timestamp="2025-09-21T03:59:38 IST">
  <testcase classname="HRM_Framework.HRM_Framework.Login_Test" name="validLogin" time="4.359"/>
  <testcase classname="HRM_Framework.HRM_Framework.Login_Test" name="invalidLogin" time="3.979">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at HRM_Framework.HRM_Framework.Login_Test.invalidLogin(Login_Test.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Run on Chrome -->
